export const quiz = {
  topic: 'Chemistry - Grade 9',
  level: 'Intermediate',
  totalQuestions: 5,
  perQuestionScore: 5,
  questions: [
    {
      question: 'What is the chemical formula for hydrochloric acid?',
      choices: ['H2O', 'HCl', 'H2SO4', 'HNO3'],
      type: 'MCQs',
      correctAnswer: 'HCl',
    },
    {
      question: 'What is the pH of a solution with a hydrogen ion concentration of 1 x 10^-9 M?',
      choices: ['3', '5', '7', '9'],
      type: 'MCQs',
      correctAnswer: '9',
    },
    {
      question: 'What is the chemical symbol for mercury?',
      choices: ['Hg', 'He', 'Mg', 'Me'],
      type: 'MCQs',
      correctAnswer: 'Hg',
    },
    {
      question: 'What is the chemical formula for sulfur dioxide?',
      choices: ['SO2', 'SO3', 'CO2', 'NO2'],
      type: 'MCQs',
      correctAnswer: 'SO2',
    },
    {
      question: 'Which of the following is a characteristic of acids?',
      choices: ['Turns litmus paper blue', 'Produces hydroxide ions in solution', 'Sour taste', 'High pH value'],
      type: 'MCQs',
      correctAnswer: 'Sour taste',
    },
    {
      question: 'What is the chemical symbol for sodium?',
      choices: ['Na', 'So', 'S', 'No'],
      type: 'MCQs',
      correctAnswer: 'Na',
    },
    {
      question: 'What is the chemical formula for calcium carbonate?',
      choices: ['CaCO3', 'C6H12O6', 'CO2', 'CH4'],
      type: 'MCQs',
      correctAnswer: 'CaCO3',
    },
    {
      question: 'Which of the following is a characteristic of bases?',
      choices: ['Turns litmus paper red', 'Produces hydrogen ions in solution', 'Bitter taste', 'Low pH value'],
      type: 'MCQs',
      correctAnswer: 'Bitter taste',
    },
    {
      question: 'What is the chemical symbol for potassium?',
      choices: ['K', 'P', 'Ka', 'Km'],
      type: 'MCQs',
      correctAnswer: 'K',
    },
    {
      question: 'What is the chemical formula for nitric acid?',
      choices: ['HNO2', 'HNO3', 'H2SO4', 'HCl'],
      type: 'MCQs',
      correctAnswer: 'HNO3',
    },
    {
      question: 'Which of the following is an example of a noble gas?',
      choices: ['Neon', 'Nitrogen', 'Oxygen', 'Hydrogen'],
      type: 'MCQs',
      correctAnswer: 'Neon',
    },
    {
      question: 'What is the chemical symbol for chlorine?',
      choices: ['Cl', 'C', 'Ch', 'Ce'],
      type: 'MCQs',
      correctAnswer: 'Cl',
    },
    {
      question: 'What is the chemical formula for sulfuric acid?',
      choices: ['H2SO4', 'H2O', 'HCl', 'HNO3'],
      type: 'MCQs',
      correctAnswer: 'H2SO4',
    },
    {
      question: 'Which of the following is a characteristic of neutralization reactions?',
      choices: ['Release of heat', 'Formation of water', 'Formation of gas', 'All of the above'],
      type: 'MCQs',
      correctAnswer: 'All of the above',
    },
    {
      question: 'What is the chemical formula for hydrofluoric acid?',
      choices: ['HF', 'H2SO4', 'HNO3', 'HCl'],
      type: 'MCQs',
      correctAnswer: 'HF',
    },
  ],
};
