export const quiz = {
  topic: 'Forces in Physics',
  level: 'Beginner',
  totalQuestions: 4,
  perQuestionScore: 5,
  questions: [
    {
      question: 'What is the formula for calculating force?',
      choices: ['F = ma', 'F = mv', 'F = ms', 'F = me'],
      type: 'MCQs',
      correctAnswer: 'F = ma',
    },
    {
      question: 'Which unit is used to measure force?',
      choices: ['Newton', 'Joule', 'Watt', 'Pascal'],
      type: 'MCQs',
      correctAnswer: 'Newton',
    },
    {
      question: 'What happens to an object when an unbalanced force acts on it?',
      choices: ['It accelerates', 'It decelerates', 'It remains at rest', 'It gains potential energy'],
      type: 'MCQs',
      correctAnswer: 'It accelerates',
    },
    {
      question: 'According to Newton\'s third law, for every action, there is an equal and opposite...',
      choices: ['Action', 'Force', 'Reaction', 'Acceleration'],
      type: 'MCQs',
      correctAnswer: 'Reaction',
    },
    {
      question: 'What is the SI unit of magnetic field?',
      choices: ['Tesla', 'Weber', 'Gauss', 'Henry'],
      type: 'MCQs',
      correctAnswer: 'Tesla',
    },
    {
      question: 'What is the direction of the magnetic field inside a magnet?',
      choices: ['From North to South', 'From South to North', 'From West to East', 'From East to West'],
      type: 'MCQs',
      correctAnswer: 'From North to South',
    },
    {
      question: 'What is the SI unit of mass?',
      choices: ['Newton', 'Kilogram', 'Meter', 'Second'],
      type: 'MCQs',
      correctAnswer: 'Kilogram',
    },
    {
      question: 'Which of the following is a unit of distance?',
      choices: ['Watt', 'Liter', 'Joule', 'Meter'],
      type: 'MCQs',
      correctAnswer: 'Meter',
    },
    {
      question: 'Which of the following is an example of a renewable energy source?',
      choices: ['Coal', 'Oil', 'Wind', 'Natural Gas'],
      type: 'MCQs',
      correctAnswer: 'Wind',
    },
    {
      question: 'What is the force that pulls objects towards the center of the Earth?',
      choices: ['Friction', 'Magnetism', 'Gravity', 'Tension'],
      type: 'MCQs',
      correctAnswer: 'Gravity',
    },
    {
      question: 'What type of energy does a moving bicycle have?',
      choices: ['Potential energy', 'Kinetic energy', 'Electrical energy', 'Solar energy'],
      type: 'MCQs',
      correctAnswer: 'Kinetic energy',
    },
    {
      question: 'Which of the following is a non-renewable energy source?',
      choices: ['Solar power', 'Wind power', 'Coal', 'Hydroelectric power'],
      type: 'MCQs',
      correctAnswer: 'Coal',
    },
    {
      question: 'What is the process by which water vapor turns into liquid water?',
      choices: ['Sublimation', 'Condensation', 'Evaporation', 'Melting'],
      type: 'MCQs',
      correctAnswer: 'Condensation',
    },
    {
      question: 'What is the SI unit of time?',
      choices: ['Meter', 'Second', 'Kilogram', 'Newton'],
      type: 'MCQs',
      correctAnswer: 'Second',
    },
    {
      question: 'Which of the following is an example of a push force?',
      choices: ['Pulling a rope', 'Kicking a ball', 'Closing a door', 'Pushing a book'],
      type: 'MCQs',
      correctAnswer: 'Pushing a book',
    },
    {
      question: 'What happens to an object when it is in motion and no force is acting on it?',
      choices: ['It slows down', 'It speeds up', 'It stops moving', 'It continues moving at a constant speed'],
      type: 'MCQs',
      correctAnswer: 'It continues moving at a constant speed',
    },
    {
      question: 'What is the force that opposes motion between two surfaces in contact?',
      choices: ['Friction', 'Gravity', 'Tension', 'Magnetism'],
      type: 'MCQs',
      correctAnswer: 'Friction',
    },
    {
      question: 'What is the SI unit of temperature?',
      choices: ['Kelvin', 'Celsius', 'Fahrenheit', 'Joule'],
      type: 'MCQs',
      correctAnswer: 'Kelvin',
    },
    {
      question: 'Which of the following is an example of a contact force?',
      choices: ['Gravity', 'Friction', 'Magnetism', 'Tension'],
      type: 'MCQs',
      correctAnswer: 'Friction',
    },
    {
      question: 'What is the energy possessed by an object due to its position or condition?',
      choices: ['Kinetic energy', 'Potential energy', 'Mechanical energy', 'Thermal energy'],
      type: 'MCQs',
      correctAnswer: 'Potential energy',
    },
    {
      question: 'What is the force that pulls objects towards each other?',
      choices: ['Tension', 'Gravity', 'Friction', 'Magnetism'],
      type: 'MCQs',
      correctAnswer: 'Gravity',
    },
    {
      question: 'What is the process by which a liquid turns into a gas?',
      choices: ['Sublimation', 'Condensation', 'Evaporation', 'Freezing'],
      type: 'MCQs',
      correctAnswer: 'Evaporation',
    },
    {
      question: 'Which of the following is a unit of force?',
      choices: ['Watt', 'Newton', 'Joule', 'Ampere'],
      type: 'MCQs',
      correctAnswer: 'Newton',
    },
    {
      question: 'What is the force exerted on an object due to gravity?',
      choices: ['Mass', 'Weight', 'Volume', 'Density'],
      type: 'MCQs',
      correctAnswer: 'Weight',
    },
    {
      question: 'What is the process by which a solid turns into a liquid?',
      choices: ['Sublimation', 'Condensation', 'Evaporation', 'Melting'],
      type: 'MCQs',
      correctAnswer: 'Melting',
    },
    {
      question: 'Which of the following is a renewable energy source?',
      choices: ['Coal', 'Oil', 'Solar power', 'Natural Gas'],
      type: 'MCQs',
      correctAnswer: 'Solar power',
    },
  ]
};